[package]
name = "math_helpers"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
criterion = { version = "0.7.0", features = ["html_reports"] }
rand = "0.9.2"

[[bench]]
name = "scal_bench"
harness = false
