[package]
name = "lambert_2_15_additive"
version = "0.1.0"
edition = "2024"

[dependencies]
matlab_base_wrapper = {path = "../matlab_base_wrapper"}
math_helpers = {path = "../math_helpers"}

[lib]
crate-type=["dylib"]
